$ANSIBLE_VAULT;1.1;AES256
65663838643831333530383537636236626561636263323437343230363439366366393465653331
3031316163326138373637643733643836376661323234310a613934613162353539616464373936
39623462393365326666316139356430646133623464656238383161643462663335326135653739
6433366365636134660a653663373562646535383937383464666562623038326531303164323764
33616165313233303333376139613035346435313165396666353539333132616639376265616561
61353465313936653533326131643362346262356233636164326339353732373735636134623339
62623561383933636164636531396131333032626332396463306263316465626239323432376432
36353730353335383966626532626430333066643032353866306531336338366530373561386333
34376264393737306137353031643762656366336330383530643465393931663064656564626365
61616130663938646263383562313163336461663638363831343037613261346461303837396437
61616663396337636561623138616233666232393965656661313631396632383238323139373666
30663961333763363435353966356632633338366235623033396533323764366561363134323338
35666332323036653266323566633436393963373262326137386265333135653864376166306334
6630616663633632373366306232613436643663653335313632
